ProjetoMVC/Models/Contato.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetoMVC.Models
{
    public class Contato
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }    
        public bool Ativo { get; set; }
    }
}

ProjetoMVC/Models/ErrorViewModel.cs
namespace ProjetoMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ProjetoMVC/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjetoMVC.Context;
using ProjetoMVC.Models;

namespace ProjetoMVC.Controllers
{
    public class ContatoController : Controller
    {
        private readonly AgendaContext _context;

        public ContatoController(AgendaContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var contatos = _context.Contatos.ToList();
            return View(contatos);
        } 
        public IActionResult Criar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Criar(Contato contato)
        {
            if(ModelState.IsValid)
            {
                _context.Contatos.Add(contato);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(contato);
        }
        public IActionResult Editar(int id)
        {
            var contato = _context.Contatos.Find(id);

            if (contato == null)
                return RedirectToAction(nameof(Index));

            return View(contato);
        }

        [HttpPost]
        public IActionResult Editar(Contato contato)
        {
            var contatoBanco = _context.Contatos.Find(contato.Id);

            contatoBanco.Nome = contato.Nome;
            contatoBanco.Telefone = contato.Telefone;
            contatoBanco.Ativo = contato.Ativo;

            _context.Contatos.Update(contatoBanco);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Detalhes(int id)
        {
            var contato = _context.Contatos.Find(id);

            if(contato == null)
                return RedirectToAction(nameof(Index));
            return View(contato);
        }

        public IActionResult Deletar(int id)
        {
           var contato = _context.Contatos.Find(id);

            if(contato == null)
                return RedirectToAction(nameof(Index));
            return View(contato); 
        }

        [HttpPost]
        public IActionResult Deletar(Contato contato)
        {
            var contatoBanco = _context.Contatos.Find(contato.Id);

            _context.Contatos.Remove(contatoBanco);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


    }
}

ProjetoMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ProjetoMVC.Models;

namespace ProjetoMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ProjetoMVC/Views/Contato/Criar.cshtml
@model ProjetoMVC.Models.Contato

@{
    ViewData["Title"] = "Criar novo Contato";
}

<h1>Criar novo Contato</h1>

<hr/>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Criar">
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
            </div>
             <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
            </div>
             <div class="form-group">
                <label asp-for="Ativo" class="control-label"></label>
                <input type="checkbox" asp-for="Ativo" class="form-check-input" />
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<hr/>
<br>
<div>
    <a asp-action="Index">Voltar</a>
</div>

ProjetoMVC/Views/Contato/Deletar.cshtml
@model ProjetoMVC.Models.Contato

@{
    ViewData["Title"] = "Deletar o Contato";
}

<h1 style="color:red;">Deseja Realmente Deletar o contato ? </h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nome)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nome)
        </dt>
         <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Telefone)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Telefone)
        </dt>
         <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Ativo)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Ativo)
        </dt>
    </dl>
</div>
<form asp-action="Deletar">
  <input type="submit" value="Deletar" class="btn btn-danger" />  
</form>

<br>
<a asp-action="Index">Voltar</a>

ProjetoMVC/Views/Contato/Detalhes.cshtml
@model ProjetoMVC.Models.Contato

@{
    ViewData["Title"] = "Detalhes do contato";
}

<h1>Detalhes</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nome)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nome)
        </dt>
         <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Telefone)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Telefone)
        </dt>
         <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Ativo)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Ativo)
        </dt>
    </dl>
</div>
<a asp-action="Editar" asp-route-id="@Model.Id">Editar</a>|
<a asp-action="Index">Voltar</a>

ProjetoMVC/Views/Contato/Editar.cshtml
@model ProjetoMVC.Models.Contato

@{
    ViewData["Title"] = "Editar Contato";
}

<h1>Editar Contato</h1>

<hr/>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
            </div>
             <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
            </div>
             <div class="form-group">
                <label asp-for="Ativo" class="control-label"></label>
                <input type="checkbox" asp-for="Ativo" class="form-check-input" />
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<hr/>
<br>
<div>
    <a asp-action="Index">Voltar</a>
</div>

ProjetoMVC/Views/Contato/Index.cshtml
@model IEnumerable<ProjetoMVC.Models.Contato>

@{
    ViewData["Title"] = "Listagem de Contatos";
}

<h2>Contatos</h2>

<p>
    <a asp-action="Criar">Novo Contato</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Telefone)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Ativo)
                </td>
                <td>
                    <a asp-action="Editar" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Detalhes" asp-route-id="@item.Id">Detalhes</a> |
                    <a asp-action="Deletar" asp-route-id="@item.Id">Deletar</a> 
                </td>
            </tr>
        }
    </tbody>
</table>

ProjetoMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Seja Bem Vindo !!</h1>
    <p>Use os Menus acima para navegar</p>
</div>

ProjetoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjetoMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProjetoMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>